---
- name: restart apache in systemd
  systemd:
    name: "{{ apache_service_name }}"
    state: restarted
    enabled: "{{ apache_service_enabled }}"
  become: true
  when: _ssh_local_connection
  listen: "restart apache httpd"

- name: restart apache in container
  shell: "{{ container_apache_restart_cmd }}"
  become: true
  when: _container_connection
  listen: "restart apache httpd"

- name: update nginx stage
  shell: "{{ ood_base_dir }}/nginx_stage/sbin/update_nginx_stage"
  become: true
